# Generated by Django 2.2.3 on 2020-03-01 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('subcat', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAndNumber', models.CharField(help_text='Eg. Woodlands road 26', max_length=128)),
                ('city', models.CharField(help_text='Eg. Glasgow', max_length=20)),
                ('postcode', models.CharField(help_text='Eg. G4 7AL', max_length=10)),
                ('description', models.TextField(help_text='Tell us something about you')),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('dob', models.DateField()),
                ('isSeller', models.BooleanField(default=False)),
                ('ratings', models.FloatField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('products', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuse.Category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg. Notebook', max_length=128)),
                ('description', models.TextField(help_text='Tell the buyers something about your product')),
                ('price', models.FloatField(default=0, help_text='3.50')),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('buyer', models.ForeignKey(on_delete=models.SET('This user no longer exists'), related_name='buyer', to='reuse.UserProfile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_by', to='reuse.UserProfile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuse.Subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insert title here', max_length=128)),
                ('text', models.TextField(help_text='Tell us how the seller was')),
                ('rating', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='reuse.UserProfile')),
                ('product', models.ForeignKey(on_delete=models.SET('This product no longer exists'), to='reuse.SoldProduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='reuse.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg. Notebook', max_length=128)),
                ('description', models.TextField(help_text='Tell the buyers something about your product')),
                ('price', models.FloatField(default=0, help_text='3.50')),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='reuse.UserProfile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuse.Subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
