# Generated by Django 2.2.3 on 2020-03-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='products',
        ),
    ]
