# Generated by Django 2.2.3 on 2020-03-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0003_auto_20200306_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
