# Generated by Django 2.2.3 on 2020-03-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0006_shoppingcart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentproduct',
            name='dat',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='dat',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
