# Generated by Django 2.2.3 on 2020-03-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0007_auto_20200319_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuse.Category'),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuse.Category'),
        ),
    ]
