# Generated by Django 2.2.3 on 2020-03-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0008_auto_20200320_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='streetAndNumber',
            new_name='address',
        ),
    ]
