# Generated by Django 2.2.3 on 2020-03-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0009_auto_20200320_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='reuse.UserProfile'),
        ),
    ]
