# Generated by Django 2.2.3 on 2020-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0009_auto_20200324_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_images/default-user.png', upload_to='profile_images'),
        ),
    ]
