# Generated by Django 2.2.3 on 2020-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0013_auto_20200324_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currentproduct',
            name='image1',
            field=models.ImageField(default='product_images/default.png', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='image1',
            field=models.ImageField(default='product_images/default.png', upload_to='product_images'),
        ),
    ]
