# Generated by Django 2.2.3 on 2020-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0014_auto_20200326_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentproduct',
            old_name='dat',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='soldproduct',
            old_name='dat',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='currentproduct',
            name='image2',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='currentproduct',
            name='image3',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='currentproduct',
            name='image4',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='currentproduct',
            name='image5',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
    ]
