# Generated by Django 2.2.3 on 2020-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0015_auto_20200326_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_reg',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
