# Generated by Django 2.2.3 on 2020-03-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0016_userprofile_date_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.OneToOneField(on_delete=models.SET('This product no longer exists'), to='reuse.SoldProduct'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
