# Generated by Django 2.2.3 on 2020-03-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0019_auto_20200328_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ratings',
        ),
    ]
