# Generated by Django 2.2.3 on 2020-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0020_remove_userprofile_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_images/default-user.png', max_length=255, upload_to='profile_images'),
        ),
    ]
